sudo: required
services:
  - docker

before_install:
  - docker build -t jimmyayo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jimmyayo/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-194108261858"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    "$AWS_SECRET_KEY"